### 签名
POST {{host}}/transaction/sign
Content-Type: application/json

{
  "gas": 2100,
  "private": "2b70dca49b288dda99301cf7c6067b5b90c76542318950304bc32e60feecb258",
        "to": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
  "value": 567
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("signedTx", response.body.data.signedTxData);
%}

### 广播已签名的Tx

POST {{host}}/transaction/send_sign
Content-Type: application/json

{
  "signedTx": "{{signedTx}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("txHash", response.body.data.tx_hash);
%}

### 创建裸交易
POST {{host}}/transaction/raw
Content-Type: application/json

{
  "gas": 2100,
  "private": "2b70dca49b288dda99301cf7c6067b5b90c76542318950304bc32e60feecb258",
  "to": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
  "value": 456
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("rawTx", response.body.data.rawTx);
%}

### 发送裸交易
POST {{host}}/transaction/send_raw
Content-Type: application/json

{
  "rawTx": "{{rawTx}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("txHash", response.body.data.tx_hash);
%}

### 使用ethclient查询 Transaction
POST {{host}}/tx
Content-Type: application/json

{
  "txHash": "{{txHash}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
%}

### 使用 blockNumber 查询 transactions
GET localhost:8081/txs?block=3656483&p=2
Content-Type: application/json

{
  "number": 1322437
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
%}

###



### 查询指定区块账户余额

#POST {{host}}/balance
#Content-Type: application/json
#
#{
#  "address": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
#  "block_number": 17350888
#}
#
#> {%
#    client.test("Request executed successfully", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#    client.test("Request code success", function() {
#        client.assert(response.body.code === 200, "Response code is not 200");
#    });
#%}

### 查询指定区块的nonce

#POST {{host}}/nonce
#Content-Type: application/json
#
#{
#  "address": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
#  "block_number": 17350888
#}
#
#> {%
#    client.test("Request executed successfully", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#    client.test("Request code success", function() {
#        client.assert(response.body.code === 200, "Response code is not 200");
#    });
#%}
