### 签名
POST {{host}}/tx/sign
Content-Type: application/json

{
  "gas": 2100,
  "private": "2b70dca49b288dda99301cf7c6067b5b90c76542318950304bc32e60feecb258",
        "to": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
  "value": 567
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("signedTx", response.body.data.signed_tx_data);
%}

### 广播已签名的Tx

POST {{host}}/tx/send_sign
Content-Type: application/json

{
  "signedTx": "{{signedTx}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("txHash", response.body.data.tx_hash);
%}

### 创建裸交易
POST {{host}}/tx/raw
Content-Type: application/json

{
  "gas": 2100,
  "private": "2b70dca49b288dda99301cf7c6067b5b90c76542318950304bc32e60feecb258",
  "to": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
  "value": 456
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("rawTx", response.body.data.raw_tx);
%}

### 发送裸交易
POST {{host}}/tx/send_raw
Content-Type: application/json

{
  "rawTx": "{{rawTx}}"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Request code success", function() {
        client.assert(response.body.code === 200, "Response code is not 200");
    });
    client.global.set("txHash", response.body.data.tx_hash);
%}

### 查询指定区块账户余额

#POST {{host}}/balance
#Content-Type: application/json
#
#{
#  "address": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
#  "block_number": 17350888
#}
#
#> {%
#    client.test("Request executed successfully", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#    client.test("Request code success", function() {
#        client.assert(response.body.code === 200, "Response code is not 200");
#    });
#%}

### 查询指定区块的nonce

#POST {{host}}/nonce
#Content-Type: application/json
#
#{
#  "address": "0xc0749b740cAe8768b89547fEdbC33eB45afC236c",
#  "block_number": 17350888
#}
#
#> {%
#    client.test("Request executed successfully", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#    client.test("Request code success", function() {
#        client.assert(response.body.code === 200, "Response code is not 200");
#    });
#%}
